fake = false
log_level = "INFO"
zmq_auto_kill_timedelta = 5
zmq_auto = false
test = false

[rcms]
host = "https://172.27.6.43:443"
rcms_rest_api = "http://172.27.6.43:8181"
wcs_rest_api = "http://172.27.6.43:8090"
hash = "sha256"
username = "twh"
password = "Hik@123456"

[redis]
host = "127.0.0.1"
port = 6379
db = 2

[web]
host = "0.0.0.0"
port = 8000
workers = 1

[agv]
username = "root"
password = "hiklinux"

[chat]
expire_days = 7
